site_name: django-api
site_description: Django API practice
repo_url: https://github.com/jpark2320/django-api
site_dir: site
copyright: Copyright &copy; 2019, <a href="https://github.com/jpark2320">jpark2320</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
